# Generated by Django 5.2.3 on 2025-06-30 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumnos',
            old_name='carrera',
            new_name='curso',
        ),
    ]
