# Generated by Django 5.2.3 on 2025-06-30 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnos',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='matricula',
        ),
        migrations.AddField(
            model_name='alumnos',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='curso',
            field=models.CharField(choices=[('Python', 'Python'), ('Base de Datos', 'Base de Datos'), ('JavaScript', 'JavaScript'), ('POO', 'POO'), ('MongoDB', 'MongoDB')], default='Python', max_length=20, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='fotos'),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='turno',
            field=models.CharField(choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino')], max_length=20),
        ),
    ]
