# Generated by Django 5.2.3 on 2025-06-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='texto',
            field=models.TextField(blank=True, null=True, verbose_name='Comentario'),
        ),
    ]
