# Generated by Django 5.2.3 on 2025-06-30 02:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_comentario_texto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='texto',
        ),
        migrations.AddField(
            model_name='comentario',
            name='coment',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Comentario'),
        ),
    ]
