# Generated by Django 5.2.3 on 2025-06-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_remove_comentario_texto_comentario_coment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del curso')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('cupo', models.IntegerField(verbose_name='Cupo máximo')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Está activo?')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cursos', verbose_name='Imagen del curso')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['created'],
            },
        ),
    ]
