# Generated by Django 5.2.3 on 2025-06-30 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='duracion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Duración'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inicio'),
        ),
    ]
