# Generated by Django 5.2.3 on 2025-06-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_curso_duracion_alter_curso_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='turno',
            field=models.CharField(blank=True, choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino')], max_length=20, null=True, verbose_name='Turno'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='duracion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Duración (Horas)'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fotos', verbose_name='Imagen del curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(choices=[('Python', 'Python'), ('Base de Datos', 'Base de Datos'), ('JavaScript', 'JavaScript'), ('POO', 'POO'), ('MongoDB', 'MongoDB')], default='Python', max_length=20, verbose_name='Nombre del curso'),
        ),
    ]
